// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ThomasonAlgorithm.Demo;

#nullable disable

namespace ThomasonAlgorithm.Demo.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ThomasonAlgorithm.Demo.Models.CubicGraphExperiment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Dictionary<int, int>>("ChordLengths")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("chord_lengths");

                    b.Property<int>("KLow")
                        .HasColumnType("integer")
                        .HasColumnName("K_low");

                    b.Property<int>("KUp")
                        .HasColumnType("integer")
                        .HasColumnName("K_up");

                    b.Property<int>("LollipopStepsNumber")
                        .HasColumnType("integer")
                        .HasColumnName("lollipop_steps_number");

                    b.Property<int>("MaxChordLength")
                        .HasColumnType("integer")
                        .HasColumnName("max_chord_length");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<int>("VerticesNumber")
                        .HasColumnType("integer")
                        .HasColumnName("vertices_number");

                    b.HasKey("Id")
                        .HasName("pk_cubic_graph_experiments");

                    b.ToTable("cubic_graph_experiments", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
